### NUMPY array operation

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing", arr[2:7])
print("with step", arr[1:8:2])
print("Negative indexing", arr[-3])


Basic slicing [3 4 5 6 7]
with step [2 4 6 8]
Negative indexing 8


In [5]:
arr_2d = np.array([ [1,2,3],
                    [4,5,6],
                    [7,8,9]
                    ])
print("Specific element", arr_2d[1,2])
print("entire row:", arr_2d[1])
print("Entire row:", arr_2d[:,1])

Specific element 6
entire row: [4 5 6]
Entire row: [2 5 8]


### SORTING

In [6]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,4],[2,7],[0,9]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis = 1))


Sorted array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[3 4]
 [2 7]
 [0 9]]


### FLITER

In [ ]:
numbers = np.array([[1,2,3,4,5,6,7,8,9,20]])
even_number = numbers[numbers % 2 == 0]
print(even_number
      )

### Filter with mask

In [10]:
numbers = np.array([[1,2,3,4,5,6,7,8,9,20]])
mask = numbers > 5
print("Number greater than 5", numbers[mask])

Number greater than 5 [ 6  7  8  9 20]


### fancy indexing vs np.where()

In [9]:
import numpy as np

where_result = np.where(numbers > 5)
print(where_result)
print("Np where", numbers[where_result])

(array([0, 0, 0, 0, 0]), array([5, 6, 7, 8, 9]))
Np where [ 6  7  8  9 20]


In [10]:

#use where( condition , x , y)
# x = return the number in state if condition statfiys 
# y = if the condition is false then return number as per the y clause

condition_array = np.where(numbers > 5, numbers*2 , numbers) 
print(condition_array)

[[ 1  2  3  4  5 12 14 16 18 40]]


### ADDING and Removing the data

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined  = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibitly

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("check compatibility shapes:-", a.shape == b.shape)

check compatibility shapes:- True


In [16]:
original = np.array([[1,2],
                    [3,4]])
new_row = np.array([[5,6]])

# .vstack help to add the new row
with_new_row = np.vstack((original , new_row))
print(original)
print(with_new_row)

new__col = np.array([[7],[8]])
with_new_col = np.hstack((original, new__col))
print("with new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


In [18]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,3)
print("array after deletion: ",deleted)

array after deletion:  [1 2 3 5]
