##learn about the numpy with chai aur code


svda

In [1]:
import numpy as np

### creating array from the list


In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1d array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array:", arr_2d)

1d array: [1 2 3 4 5]
2d array: [[1 2 3]
 [4 5 6]]


### LIST vs Numpy array

In [3]:
py_list = [1,2,3]
print("Python list multiplication", py_list*2)

np_array = np.array([1,2,3])
print("python array multiplication:", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List is operation time", time.time()- start)

start = time.time()
np_array = np.arange(10000000)*2
print("\n Numpy operation time:", time.time()- start)


Python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication: [2 4 6]

 List is operation time 0.9974241256713867

 Numpy operation time: 0.06836414337158203


### creating array from scratch


In [4]:
zeros = np.zeros((3,4))
print("zeroes array: \n",zeros)

ones = np.ones((2,3))
print("one array: \n", ones)

full = np.full((2,2),7)
print("full array: \n" , full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0,10,2)
print("sequence array: \n", sequence)

zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.28086671 0.73069654 0.13380278]
 [0.67792157 0.40195223 0.48317228]]
sequence array: 
 [0 2 4 6 8]


### Vector , matrix and tensor

In [5]:
vector = np.array([1,2,3])
print("vector: ", vector)

martix = np.array([[1,2,3,4],
                    [2,3,4,5]])
print("Matrix:", martix)

Tensor = np.array([[[1,2,3],[4,5,6]],
                    [[3,4,5],[7,8,9]]])
print("Tensor: ",Tensor)

vector:  [1 2 3]
Matrix: [[1 2 3 4]
 [2 3 4 5]]
Tensor:  [[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [7 8 9]]]


### Array properties

In [6]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape", arr.shape) # tell us about the row and column
print("Dimesion", arr.ndim) #tell about dimension
print("Size", arr.size) #tell us about the number of data availabe
print("Dtype", arr.dtype) # tell us about the data type

shape (2, 3)
Dimesion 2
Size 6
Dtype int64


### Array reshaping

In [7]:
arr = np.arange(12)
print("original array", arr)

reshape = arr.reshape((3,4))
print("Reshape array", reshape )

flatten = reshape.flatten()
print("\n Flattern array", flatten)

# ravel (return view, instead of copy)
raveled = reshape.ravel()
print('\n raveled array', raveled)

transpose = reshape.T
print("\n Transpose", transpose)


original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattern array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
